language: node_js
node_js:
  - "node"
before_install:
  - npm install -g grunt-cli
  - npm install -g http-server
install:
  - npm install
services:
  - http-server
script: grunt mocha
after_success: "./travis.sh"
